# Project: BRKGA
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Decoder.o Instance.o
LINKOBJ  = main.o Decoder.o Instance.o
LIBS     = -L"C:/Users/saryg/Dev-Cpp/MinGW64/lib" -L"C:/Users/saryg/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/saryg/Dev-Cpp/MinGW64/include" -I"C:/Users/saryg/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/saryg/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/saryg/Dev-Cpp/MinGW64/include" -I"C:/Users/saryg/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/saryg/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/saryg/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = BRKGA.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Decoder.o: Decoder.cpp
	$(CPP) -c Decoder.cpp -o Decoder.o $(CXXFLAGS)

Instance.o: Instance.cpp
	$(CPP) -c Instance.cpp -o Instance.o $(CXXFLAGS)
